### PR TITLE
fix!(jans-cedarling): fix cedarling-properties docs to be more proper

### LINKED ISSUE #10748: fix(jans-cedarling): fix cedarling-properties docs to be more proper
We need to fix documentation:
- make sure that documentation show what parameters are needed to be specified as required
- make sure that is written that for `CEDARLING_USER_AUTHZ` and `CEDARLING_WORKLOAD_AUTHZ` at least one should be specified
- fix or remove doc from python pyi file (because some statement is wrong), and it would be easier to store only one set of docs [here](https://docs.jans.io/head/cedarling/cedarling-properties/) )

Also, `CEDARLING_ID_TOKEN_TRUST_MODE` in doc can contain `None` but in real `none`.

### PR DESCRIPTION
**Pull request by olehbozhok**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Improve documentation. Fix name of some keys. Added information about required bootstrap properties keys.

#### Target issue
  
  [link](https://github.com/JanssenProject/jans/issues/10748)
  
  
closes #10748 

#### Implementation Details
  
- align config parameter names against Cedarling-Nativity-Plan
- add section `Required keys for startup`
- now if key `CEDARLING_TOKEN_CONFIGS ` is absent `serde` show key in error

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

### CODE REVIEW

File: jans-cedarling/cedarling/src/bootstrap_config/raw_config/config.rs [hunk 1]
```diff
@@ -152,7 +152,7 @@ pub struct BootstrapConfigRaw {
 
     /// Configuration for token-based entities, mapping token names to their
     /// respective settings.
-    #[serde(rename = "CEDARLING_TOKEN_CONFIGS", default)]
+    #[serde(rename = "CEDARLING_TOKEN_CONFIGS")]
```
Comment (rmarinn) [inline jans-cedarling/cedarling/src/bootstrap_config/raw_config/config.rs]: why remove the `serde(default)` here? won't the deserialization fail if the `CEDARLING_TOKEN_CONFIGS` is not provided? the `TokenConfigs` struct implements `Default` in `raw_config/token_settings.rs`.

Are we requiring the user to set this bootstrap config now?

**Comment by rmarinn** [comment]
it also looks like python tests are failing now.

File: jans-cedarling/cedarling/src/bootstrap_config/raw_config/config.rs (hunk 1 above)
Comment (olehbozhok) [reply jans-cedarling/cedarling/src/bootstrap_config/raw_config/config.rs]: OK, I missed that `TokenConfigs` have custom implementation of `Default` trait.

Comment (olehbozhok) [reply jans-cedarling/cedarling/src/bootstrap_config/raw_config/config.rs]: fixed https://github.com/JanssenProject/jans/pull/10788/commits/407f5d8a7e5f1b5ffbd156a6089cff838650f9e6
and added doc https://github.com/JanssenProject/jans/pull/10788/commits/a6052ed3b3460f5eed9febf07ebc72480c91016b

**Review by nynymike — APPROVED** [review]

**Review by SafinWasi — APPROVED** [review]
Looks good to me. I changed the PR title a bit to include breaking change `!`
