### PR TITLE
fix(jans-cedarling): add returning error on build entity with schema

### LINKED ISSUE #13038: fix(jans-cedarling): early error returns in build_entity_attrs cause test failures
**Describe the bug**
Adding early error returns in `build_entity_attrs_with_shape` function causes multiple tests to fail.

**To Reproduce**
1. Add early return in `jans-cedarling/cedarling/src/entity_builder/build_entity_attrs.rs` and update `jans-cedarling/cedarling/src/entity_builder/error.rs`
3. Run the tests with `cargo test -p cedarling`
4. Multiple tests that previously passed will now fail due to early error returns

To check add the below code:
- In `build_entity_attrs.rs` line 153 add: 
```rust
    if !errs.is_empty() {
        return Err(BuildAttrsErrorVec::from(errs));
    }
```
- In `error.rs` add:
```rust
impl From<Vec<BuildAttrsError>> for BuildAttrsErrorVec {
    fn from(errs: Vec<BuildAttrsError>) -> Self {
        Self(errs)
    }
}
```

**Expected behavior**
Tests should continue to pass.

**Additional context**

The issue appears to be that the new early error return changes the flow of error handling. The existing code doesn't return errors so maybe this is wanted by design, and adding the early return may be redundant or interfering with the existing error handling logic.

### PR DESCRIPTION
**Pull request by olehbozhok**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
  - updated function `build_entity_attrs_with_shape` to return errors on building entity.
  - updated the related method that builds multiple issuer authorization entities
  - updated related unit tests

#### Target issue
  
  
  
  
closes #13038

#### Implementation Details
  

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error reporting by collecting and reporting all missing required entity attributes simultaneously instead of stopping at the first missing item.

* **Improvements**
  * Enhanced entity attribute building with automatic injection of token type and validation timestamp metadata.
  * Optimized default entity resolution for better performance.

### CODE REVIEW

**Comment by mo-auto** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/janssenproject/pr-checks/4fe2022d-7abd-454f-834e-2fdb0401e04c?refs=167b9a5e5f52f7afc3c31e8c4e80bc89f9d604c5&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by olehbozhok** [comment]
@coderabbitai review

File: jans-cedarling/cedarling/src/entity_builder/error.rs [hunk 1]
```diff
@@ -72,7 +72,7 @@ pub enum BuildEntityErrorKind {
 }
 
 #[derive(Debug, Error)]
-pub struct BuildAttrsErrorVec(Vec<BuildAttrsError>);
+pub struct BuildAttrsErrorVec(pub Vec<BuildAttrsError>);
```
Comment (dagregi) [inline jans-cedarling/cedarling/src/entity_builder/error.rs:75]: Maybe using an `impl` would be better rather than making the inner field public?

Comment (olehbozhok) [reply jans-cedarling/cedarling/src/entity_builder/error.rs:75]: nothing wrong with making it public. type `BuildAttrsError` is public.
