### PR TITLE
fix(cedarling_wasm): init fails when JWT signature and status validation are enabled 

### LINKED ISSUE #13852: fix(cedarling_wasm): init fails when JWT signature and status validation are enabled
**Describe the bug**

Cedarling initializes successfully with `CEDARLING_JWT_SIG_VALIDATION` and `CEDARLING_JWT_STATUS_VALIDATION` enabled when using the Python or Java bindings, but the **WASM/browser** binding fails during initialization. The browser console shows  a **`RuntimeError: unreachable`** originating from the WASM module (e.g. `cedarling_wasm_bg.wasm`), so the app cannot complete `init` with the same bootstrap configuration that works on native bindings.

### PR DESCRIPTION
**Pull request by haileyesus2433**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #13852

#### Implementation Details
  

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

## Summary by CodeRabbit

* **New Features**
  * Added WebAssembly support and a cross-platform asynchronous sleep helper for consistent timers.

* **Bug Fixes**
  * JWT status list parsing now returns a clear error for unsupported/corrupt encodings instead of panicking.
  * Background refresh uses the new cross-platform sleep to ensure consistent behavior across targets.

### CODE REVIEW

**Comment by mo-auto** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/janssenproject/pr-checks/743a9da7-3fa3-461a-8f90-aea8a4d99379?refs=6538929096d75bf91bbea4fd91eae6bcdb15a8e7&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: jans-cedarling/cedarling/src/jwt/status_list.rs [hunk 1]
```diff
@@ -138,27 +137,39 @@ impl TryFrom<ValidatedJwt> for StatusList {
...
+    bit_idx: u8,
+) -> Result<u8, JwtStatusError> {
+    match bit_size {
+        StatusBitSize(8) => Ok(byte),
+        StatusBitSize(1) => {
+            let offset = bit_idx;
+            Ok((byte >> offset) & 0b0000_0001)
+        },
+        StatusBitSize(2) => {
+            let offset = bit_idx * 2;
```
Comment (dagregi) [inline jans-cedarling/cedarling/src/jwt/status_list.rs:158]: why not use `let offset = bit_idx * bit_size.0` just like the original instead of hardcoded numbers?

Comment (haileyesus2433) [reply jans-cedarling/cedarling/src/jwt/status_list.rs:158]: Using bit_idx * bit_size.0 in each arm would work the same as bit_idx * 1, * 2, or * 4 for those sizes, because the matched StatusBitSize already tells you the width; the literals are only there to make the math obvious at a glance, not because the formula is different. The 8‑bit case is special anyway  the whole byte is one status, so you just return byte instead of shifting and masking like the smaller bit width hope that makes sense

**Review by dagregi — APPROVED** [review]

**Review by moabu — APPROVED** [review]

File: jans-cedarling/cedarling/src/async_sleep.rs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+//! Tokio timers require a Tokio runtime; browser WASM builds use [`gloo_timers`] instead.
+
+use std::time::Duration;
+
+/// Yields asynchronously for approximately `duration`.
+///
+/// On native targets this uses [`tokio::time::sleep`]. On WebAssembly it uses a browser
+/// timer so background work (for example status list refresh) does not require a Tokio
+/// reactor.
+pub(crate) async fn sleep(duration: Duration) {
```
Comment (olehbozhok) [inline jans-cedarling/cedarling/src/async_sleep.rs:18]: So we need to add a linter to avoid the usage `tokio::time::sleep`?

Comment (haileyesus2433) [reply jans-cedarling/cedarling/src/async_sleep.rs:18]: on wasm yes
