### PR TITLE
fix(jans-cedarling)!: role entity not being created in the unsigned interface

### LINKED ISSUE #11160: fix(jans-cedarling): authorize_unsigned not building Role entities
**Describe the bug**

Role entities are not being created in the `authorize_unsigned` interface causing policies like below:

```cedarschema
permit(
  principal in Jans::Role::"Admin",
  action,
  resource
);
```

With an entity attributes like:

```json
{
    "type": "Jans::User",
    "role": ["Admin"]
}
```

to always result in a DENY.

**To Reproduce**

1. Define a `User` entity with a `Role` parent in the Cedar schema:
```
    entity Role;
    entity User in [Role] = { ... };
```

2. Define a policy that checks for the role:
```cedarschema
permit(
  principal in Jans::Role::"Admin",
  action,
  resource
);
```

3. Call `cedarling::authorize_unsigned` with a principal attributes that contains a Role
```json
{
    "type": "Jans::User",
    "role": ["Admin"]
}
```

4. Get a `DENY` result

**Expected behavior**

- The result should be `ALLOW`
- The `Role` entity should be created

### PR DESCRIPTION
**Pull request by rmarinn**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

This PR fixes the issue where `Role` entities are not getting created in the unsigned interface.

#### Target issue
  
closes #11160

#### Implementation Details

- Fixed the issue in the unsigned interface where Role entities are not getting created.

##### New Implementations

- A new bootstrap property called `CEDARLING_UNSIGNED_ROLE_ID_SRC` was added so that Cedarling knows what to use when creating a `Role` entity in the unsigned interface.
- A new rust example has been added which uses the unsigned interface: `authorize_unsigned.rs`

##### Breaking changes

- `EntityData.payload` has been renamed to `EntityData.attributes`.

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

### CODE REVIEW

File: jans-cedarling/cedarling/src/entity_builder/entity_id_getters.rs [hunk 1]
```diff
@@ -52,7 +62,10 @@ pub fn get_first_valid_entity_id(id_srcs: &[EntityIdSrc]) -> Result<SmolStr, Bui
 pub fn collect_all_valid_entity_ids(id_srcs: &[EntityIdSrc]) -> Vec<SmolStr> {
     id_srcs
         .iter()
-        .filter_map(|src| src.token.get_claim_val(src.claim))
+        .filter_map(|src| match src {
+            EntityIdSrc::Token { token, claim } => token.get_claim_val(claim),
+            EntityIdSrc::String(_) => todo!(),
```
[the remark this answers is not in the document]
Comment (rmarinn) [reply jans-cedarling/cedarling/src/entity_builder/entity_id_getters.rs]: fixed in [9fcb0f7](https://github.com/JanssenProject/jans/pull/11176/commits/9fcb0f71370d840c366766444e8bce8a9aed1e59)

File: docs/cedarling/cedarling-properties.md [hunk 2]
```diff
@@ -21,6 +21,7 @@ These Bootstrap Properties control default application level behavior.
 * **`CEDARLING_MAPPING_USER`** : Name of Cedar User schema entity if we don't want to use default. When specified cedarling try build defined entity (from schema) as user instead of default `User` entity defined in `cedar` schema. Works in namespace defined in the policy store.
 * **`CEDARLING_MAPPING_WORKLOAD`** : Name of Cedar Workload schema entity
 * **`CEDARLING_MAPPING_ROLE`** : Name of Cedar Role schema entity
+* **`CEDARLING_UNSIGNED_ROLE_ID_SRC`** : The attribute that will be used to create the Role entity when using the. Defaults to `"role"`.
```
Comment (olehbozhok) [inline docs/cedarling/cedarling-properties.md]: `when using the.` Looks like sentence isn't finished.

Comment (olehbozhok) [reply docs/cedarling/cedarling-properties.md]: Should we have something like this when use tokens?

File: jans-cedarling/cedarling/examples/authorize_unsigned.rs [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+
+            decision_log_default_jwt_id: "jti".to_string(),
+            decision_log_user_claims: vec!["client_id".to_string(), "username".to_string()],
+            decision_log_workload_claims: vec!["org_id".to_string()],
+            id_token_trust_mode: IdTokenTrustMode::None,
+            principal_bool_operator: JsonRule::new(serde_json::json!({
+                "or" : [
+                    {"===": [{"var": "Jans::User"}, "ALLOW"]}
+                ]
+            }))
```
Comment (olehbozhok) [inline jans-cedarling/cedarling/examples/authorize_unsigned.rs]: I think we can simplify
```suggestion
            principal_bool_operator: JsonRule::new(
                serde_json::json!({"===": [{"var": "Jans::User"}, "ALLOW"]}),
            )
            .unwrap(),
```

File: jans-cedarling/cedarling/src/authz/request.rs [hunk 4]
```diff
@@ -83,7 +83,7 @@ pub struct RequestUnsigned {
     pub context: Value,
 }
 
-/// Cedar policy entity data
+/// Cedar policy resource data
```
Comment (olehbozhok) [inline jans-cedarling/cedarling/src/authz/request.rs]: `EntityData` represent the data of an entity in a Cedar policy. Not only resource. 


```suggestion
/// Cedar policy entity data
```

File: jans-cedarling/cedarling/src/entity_builder/build_principal_entity.rs [hunk 5]
```diff
@@ -33,19 +44,15 @@ impl EntityBuilder {
...
-                .into_iter()
-                .fold(HashMap::new(), |mut acc, attrs| {
-                    acc.extend(attrs);
-                    acc
-                })
+            attrs.into_iter().fold(HashMap::new(), |mut acc, attrs| {
+                acc.extend(attrs);
+                acc
+            })
         } else {
```
Comment (olehbozhok) [inline jans-cedarling/cedarling/src/entity_builder/build_principal_entity.rs:53]: We can simplify code to 

```suggestion
            HashMap::from_iter(attrs.into_iter().flatten())
```

**Comment by rmarinn** [comment]
> How about adding unit tests in `cedarling/src/tests/authorize_unsigned.rs` to verify that roles work?

There are already tests in `jans-cedarling/cedarling/src/entity_builder/build_principal_entity/unsigned.rs` that verify role creation.

The `authorize_unsigned` tests should focus on policy evaluation, like the other tests in that module. Including role creation tests there would blur the separation of concerns and overload the unit tests.

File: docs/cedarling/cedarling-properties.md (hunk 2 above)
Comment (rmarinn) [reply docs/cedarling/cedarling-properties.md]: sentence fixed in [dea0d55](https://github.com/JanssenProject/jans/pull/11176/commits/dea0d55d9d13e0f685c5be0345bb0f6a26b55fc2).

> Should we have something like this when use tokens?

We have `role_mapping` in the [token_metadata schema](https://docs.jans.io/head/cedarling/cedarling-policy-store/#token-metadata-schema).

File: jans-cedarling/cedarling/examples/authorize_unsigned.rs (hunk 3 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/examples/authorize_unsigned.rs]: resolved in [d8ad469](https://github.com/JanssenProject/jans/pull/11176/commits/d8ad46917e945a4bc0960340eb6166ce1f5581a4)

File: jans-cedarling/cedarling/src/authz/request.rs (hunk 4 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/authz/request.rs]: resolved in [2c95fc1](https://github.com/JanssenProject/jans/pull/11176/commits/2c95fc1678a6caec0e70912a3a2ca733307b9270)

File: jans-cedarling/cedarling/src/entity_builder/build_principal_entity.rs (hunk 5 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/entity_builder/build_principal_entity.rs:53]: resolved in [b5a8d69](https://github.com/JanssenProject/jans/pull/11176/commits/b5a8d695820e665fb149787f070e2f5da263e5d1)

**Review by olehbozhok — APPROVED** [review]

**Review by SafinWasi — APPROVED** [review]
Looks good to me. Role creation and RBAC policy works on python example.
