### PR TITLE
test(jans-cedarling): rectify intermittent failure in get_token_claim_type_boolean_error

### LINKED ISSUE #9778: test(jans-cedarling): rectify intermittent failure in get_token_claim_type_boolean_error
Failure of test `authz::entities::get_token_claim_type_boolean_error` is intermittent. Seems to pass on the first test run, but subsequent runs occasionally fail, approximately 1 in 5 on my setup.

To reproduce:

`cargo test get_token_claim_type_boolean_error`

### PR DESCRIPTION
**Pull request by djellemah**
docs: only a fix for an existing test.

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

Failure of test `authz::entities::get_token_claim_type_boolean_error` is intermittent. Seems to pass on the first test run, but subsequent runs occasionally fail, approximately 1 in 5 on my setup.

To reproduce:

`cargo test get_token_claim_type_boolean_error`

#### Target issue

https://github.com/JanssenProject/jans/issues/9778

#### Implementation Details

Schema requires a `String` for `entity_uid_key`, but test fixture data contains `i64`.

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

Closes #9778,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @djellemah, You did not reference an open issue in your [PR](9777). I attempted to create an [issue](#9778) for you.    
 Please update that [issues'](#9778) title and body and make sure I correctly referenced it in the above PRs body.

**Review by rmarinn — APPROVED** [review]
Looks good to me, thanks for fixing this.

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs [hunk 1]
```diff
@@ -250,7 +250,8 @@ fn get_token_claim_type_boolean_error() {
         "test_id_key": "test_id",
         "string_key": "test string",
         "long_key": 1234,
-        "entity_uid_key": 123,
+        "entity_uid_key": "ff910f15-d5a4-4227-828e-11cb8463f1b7",
+        // This will trigger the type error, because it's not a bool.
```
Comment (rmarinn) [inline jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: probably just don't forget to remove this comment before merging. it only makes sense reading from the PR.

**Review by rmarinn — CHANGES_REQUESTED** [review]

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs [hunk 2]
```diff
@@ -263,16 +264,16 @@ fn get_token_claim_type_boolean_error() {
...
         got_type,
-        ..
+        expected_type,
     }) = entity_creation_error
     {
         let json_attr_value = json.as_object().unwrap().get(test_key).unwrap();
         let origin_type = GetTokenClaimValue::json_value_type_name(json_attr_value);
 
-        assert!(key == test_key, "expected key: {test_key}, but got: {key}");
+        assert!(key == test_key, "expected key: {test_key}, but got: {key} with schema expected_type {expected_type}");
```
Comment (abaghinyan) [inline jans-cedarling/cedarling/src/authz/entities/test_create.rs]: Just a minor change to keep the consistency. 
Add ":" after expected_type
`"expected` key: {test_key}, but got: {key} with schema expected_type: {expected_type}"`

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs [hunk 3]
```diff
@@ -263,16 +264,16 @@ fn get_token_claim_type_boolean_error() {
...
         assert!(
             got_type == origin_type,
-            "expected type: {origin_type}, but got: {got_type}"
+            "expected type: {origin_type}, but got: {got_type} with schema expected_type {expected_type}"
```
Comment (abaghinyan) [inline jans-cedarling/cedarling/src/authz/entities/test_create.rs]: Same here: 
`"expected` type: {origin_type}, but got: {got_type} with schema expected_type: {expected_type}"`

**Review by abaghinyan — COMMENTED** [review]
Just a minor change before approving

**Comment by duttarnab** [comment]
The following points are not followed from [Contribution Guidelines](https://docs.jans.io/v1.1.5/CONTRIBUTING/)
```
PR should only have changes related to target feature or issue. Create a separate PR for formatting or other quick bug fixes
```
The GH issue should have change description covered in PR.

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs (hunk 1 above)
Comment (djellemah) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: I deliberately left it in the PR.

My reasoning is: text fixtures like this are mostly made of placeholder data, with only one or two values that are actually used in the test. I've found it's generally a good idea to comment on those in-use values to clarify the intent. In this case, why is the in-use value `123` rather than `1572` or `true` or `false` or `"some random string"`.

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs (hunk 2 above)
Comment (djellemah) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs]: I would agree with your point on consistency if this was a log string, or a display string, or something that was output in the normal course of running the code.

But it's just an error string in case this test fails sometime in the future. Not sure it's worthwhile making an issue of something like that.

But I'll change it.

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs (hunk 1 above)
Comment (olehbozhok) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: If we want to add this kind of comment. I feel like we need to add comment like this not only in `get_token_claim_type_boolean_error` but also in 
- `get_token_claim_type_string_error`
- `get_token_claim_type_long_error`
- `get_token_claim_type_entity_uid_error`
and maybe in
- `get_token_claim_cedar_typename_error`
- `get_token_claim_cedar_typename_in_attr_error`

**Review by abaghinyan — APPROVED** [review]

**Review by olehbozhok — CHANGES_REQUESTED** [review]
If we want to add this kind of comment. I feel like we need to add comment like this

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs (hunk 1 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: oh okay, i didn't realize that this was being used for a test. I can't see the whole file from the "Files changed" tab so i thought that this was just a misconfiguration of some sort.

**Review by rmarinn — DISMISSED** [review]

File: jans-cedarling/cedarling/src/authz/entities/test_create.rs (hunk 1 above)
Comment (djellemah) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: > If we want to add this kind of comment. I feel like we need to add comment like this not only in get_token_claim_type_boolean_error but also in ...

Sure, I can do that.

Comment (djellemah) [reply jans-cedarling/cedarling/src/authz/entities/test_create.rs:257]: @olehbozhok I don't yet know enough about schemas to make sensible comments for `get_token_claim_cedar_typename_error` and `get_token_claim_cedar_typename_in_attr_error`.

Perhaps you'd like to do those?

**Review by olehbozhok — APPROVED** [review]
Looks great

**Review by rmarinn — APPROVED** [review]

**Review by abaghinyan — APPROVED** [review]

**Review by duttarnab — APPROVED** [review]
