### PR TITLE
fix(terraform-provider-jans): update terraform module

### LINKED ISSUE #9465: fix(terraform-provider-jans): update terraform module with the API changes for 1.1.5
Update terraform provider with the latest API changes in Janssen for v1.1.5

### PR DESCRIPTION
**Pull request by moabu**
Bug Fixes

* documentation 
* update API and sync with jans updates 
Closes #9465,

### CODE REVIEW

File: terraform-provider-jans/jans/api_app_configuration.go [hunk 1]
```diff
@@ -28,43 +28,47 @@ type AssetDirMapping struct {
...
-	AgamaConfiguration          AgamaConfiguration        `schema:"agama_configuration" json:"agamaConfiguration"`
-	AuditLogConf                AuditLogConf              `schema:"audit_log_conf" json:"auditLogConf"`
-	DataFormatConversionConf    DataFormatConversionConf  `schema:"data_format_conversion_conf" json:"dataFormatConversionConf"`
-	Plugins                     []PluginConf              `schema:"plugins" json:"plugins"`
-	AssetMgtConfiguration       AssetMgtConfiguration     `schema:"asset_mgt_configuration" json:"assetMgtConfiguration"`
+	ConfigOauthEnabled               bool                      `schema:"config_oauth_enabled" json:"configOauthEnabled"`
+	DisableLoggerTimer               bool                      `schema:"disable_logger_timer" json:"disableLoggerTimer"`
+	DisableAuditLogger               bool                      `schema:"disable_audit_logger" json:"disableAuditLogger"`
+	CustomAttributeValidationEnabled bool                      `schema:"custom_attribute_validation_enabled" json:"customAttributeValidationEnabled"`
+	ArcValidationEnabled             bool                      `schema:"arc_validation_enabled" json:"arcValidationEnabled"`
```
Comment (iromli) [inline terraform-provider-jans/jans/api_app_configuration.go]: Shouldn't it be `acrValidationEnabled`? https://github.com/JanssenProject/jans/blob/e9e9808857fa58e70e02bd2fc054e7ae15b7200c/jans-linux-setup/jans_setup/templates/jans-config-api/dynamic-conf.json#L7

File: terraform-provider-jans/jans/api_app_configuration.go [hunk 2]
```diff
@@ -28,43 +28,47 @@ type AssetDirMapping struct {
...
-	AssetServerUploadEnabled bool              `schema:"asset_server_upload_enabled" json:"assetServerUploadEnabled"`
-	AssetBaseDirectory       string            `schema:"asset_base_directory" json:"assetBaseDirectory"`
-	AssetDirMappings         []AssetDirMapping `schema:"asset_dir_mappings" json:"assetDirMappings"`
+	AssetMgtEnabled                bool              `schema:"asset_mgt_enabled" json:"assetMgtEnabled"`
+	AssetServerUploadEnabled       bool              `schema:"asset_server_upload_enabled" json:"assetServerUploadEnabled"`
+	FileExtensionValidationEnabled bool              `schema:"file_extension_validation_enabled" json:"fileExtensionValidationEnabled"`
+	ModuleNameValidationEnabled    bool              `schema:"module_name_validation_enabled" json:"moduleNameValidationEnabled"`
+	AssetBaseDirectory             string            `schema:"asset_base_directory" json:"assetBaseDirectory"`
+	JansServiceModule              []string          `schema:"jans_service_module" json:"jansServiceModule"`
+	AssetDirMappings               []AssetDirMapping `schema:"asset_dir_mappings" json:"assetDirMappings"`
```
Comment (iromli) [inline terraform-provider-jans/jans/api_app_configuration.go]: The `json:"assetDirMappings"` likely need to be rename to `json:"assetDirMapping"`? https://github.com/JanssenProject/jans/blob/e9e9808857fa58e70e02bd2fc054e7ae15b7200c/jans-linux-setup/jans_setup/templates/jans-config-api/dynamic-conf.json#L94

**Review by iromli — CHANGES_REQUESTED** [review]

**Review by iromli — APPROVED** [review]
