### PR TITLE
fix: fix array java.lang.IndexOutOfBoundsException

### LINKED ISSUE #7446: feat(jans-config-api): user is able to see the user claim on create/edit user form even if the claim is disabled
1. The disabled user claim should not be obtained using `/mgt/configuser` `GET` API (also in response of POST and PUT). 

**Note:** If the user claim has been disabled after assigning its value for one or more user then also API should not send the claim value for those users.

Clipboard - January 19, 2024 6_02 PM
Clipboard - January 19, 2024 6_03 PM

### PR DESCRIPTION
**Pull request by duttarnab**
Parent issue# https://github.com/GluuFederation/flex/issues/1566
closes #7446

### CODE REVIEW

File: jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java [hunk 1]
```diff
@@ -443,4 +443,8 @@ private String getDnForAttribute(String inum) {
         }
         return String.format("inum=%s,%s", inum, attributesDn);
     }
+
+    private static boolean isEmptyOrNullCollection(Collection<?> collection) {
+        return (collection == null || collection.isEmpty());
+    }
```
Comment (yuriyz) [inline jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java]: Approving but in future you can re-use `org.apache.commons.collections.CollectionUtils#isEmpty`

**Review by yuriyz — APPROVED** [review]

**Review by yuriyz — APPROVED** [review]

File: jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java (hunk 1 above)
Comment (duttarnab) [reply jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java]: Done

**Review by yurem — APPROVED** [review]
