### PR TITLE
fix(jans-cedarling): fix logs in jwt module not getting displayed correctly

### LINKED ISSUE #11370: fix: fix(jans-cedarling): fix logs in jwt module not getting displayed correctly -autocreated
This issue was created because no open issues were referenced in your PR (#11369).

### LINKED ISSUE #11371: fix(jans-cedarling): fix logs in jwt module not getting displayed correctly
The logs messages in the JWT module do not get displayed since they do not have a log level.

### PR DESCRIPTION
**Pull request by rmarinn**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

This PR fixes the issue where warning messages in the JWT module aren't getting printed correctly.

#### Target issue
  
closes #11371

#### Implementation Details

- The messages were not getting displayed since they were missing a logging level.
- Warning messages when getting a token not from a trusted issuer should be displayed now:
    ```
    {"id":"0196acdc-086b-721c-a8bc-0111517838fc","timestamp":"2025-05- 
   08T06:27:03.403Z","log_kind":"System","level":"INFO","msg":"Cedarling Authz initialized successfully","cedar_lang_versio
    n":"4.2.0","cedar_sdk_version":"4.3.3","pdp_id":"54ce60b5-03be-4681-8883-24f6ccb9aca2","application_id":"test_app"}
    {"id":"0196acdc-086b-721c-a8bc-0113547e39ca","timestamp":"2025-05- 
   08T06:27:03.403Z","log_kind":"System","level":"WARN","msg":"ignoring custom_token since it's from an untrusted issuer: '
    https://test.jans.org'","pdp_id":"54ce60b5-03be-4681-8883-24f6ccb9aca2","application_id":"test_app"}
    {"id":"0196acdc-086b-721c-a8bc-011489b8eb38","timestamp":"2025-05- 
   08T06:27:03.403Z","log_kind":"System","level":"WARN","msg":"ignoring userinfo_token since it's from an untrusted issuer:
     'https://test.jans.org'","pdp_id":"54ce60b5-03be-4681-8883-24f6ccb9aca2","application_id":"test_app"}
    {"id":"0196acdc-086b-721c-a8bc-01151d3c154f","timestamp":"2025-05- 
   08T06:27:03.403Z","log_kind":"System","level":"WARN","msg":"ignoring id_token since it's from an untrusted issuer: 'http
    s://test.jans.org'","pdp_id":"54ce60b5-03be-4681-8883-24f6ccb9aca2","application_id":"test_app"}
    {"id":"0196acdc-086b-721c-a8bc-0116ba448050","timestamp":"2025-05- 
   08T06:27:03.403Z","log_kind":"System","level":"WARN","msg":"ignoring access_token since it's from an untrusted issuer: '
   https://test.jans.org'","pdp_id":"54ce60b5-03be-4681-8883-24f6ccb9aca2","application_id":"test_app"}
   ```
    

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

Closes #11370,

### CODE REVIEW

**Comment by mo-auto** [comment]
Error: Hi @rmarinn, You did not reference an open issue in your [PR](11369). I attempted to create an [issue](#11370) for you.    
 Please update that [issues'](#11370) title and body and make sure I correctly referenced it in the above PRs body.

File: jans-cedarling/cedarling/src/jwt/log_entry.rs [hunk 1]
```diff
@@ -15,15 +15,16 @@ pub struct JwtLogEntry {
 }
 
 impl JwtLogEntry {
-    /// Shorthand for creating a [`LogType::System`] log.
-    pub fn system(msg: String) -> Self {
-        let base = BaseLogEntry::new_opt_request_id(LogType::System, None);
+    /// Helper for creating a [`LogLevel::WARN`] log.
+    pub fn warn(msg: String) -> Self {
```
Comment (0xtinkle) [inline jans-cedarling/cedarling/src/jwt/log_entry.rs]: JwtLogEntry only supports WARN level logs?
To make it flexible, is it better to define a function like following?
`pub fn info(msg: String, level: Option<LogLevel>) -> Self {}`

**Comment by 0xtinkle** [comment]
What are the failed CI checks?

**Comment by 0xtinkle** [comment]
I guess, we need error log entry for JWT processing failures?
something like `pub fn error(error: &str) -> Self {}`

**Review by 0xtinkle — CHANGES_REQUESTED** [review]
missing unit test in log_entry.r

**Review by 0xtinkle — COMMENTED** [review]
There is no logging for errors in JwtService, is it better to log them?

File: jans-cedarling/cedarling/src/jwt/log_entry.rs (hunk 1 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/jwt/log_entry.rs]: i refactored it here:
 [d567546](https://github.com/JanssenProject/jans/pull/11369/commits/d5675464672457fcdec3f2a667f87502abb47b6c)

**Comment by rmarinn** [comment]
> What are the failed CI checks?

just rust clippy issues.

you can check them locally by running `cargo clippy -- -D warnings`

**Comment by rmarinn** [comment]
> There is no logging for errors in JwtService, is it better to log them?

improved logging here: [ab2592d](https://github.com/JanssenProject/jans/pull/11369/commits/ab2592d10e961e16cc238fec9e83912dfe87b7de)

**Comment by rmarinn** [comment]
> missing unit test in log_entry.rs

there's two files with that name:
- jwt/log_entry.rs
- log/log_entry.rs

also, what should we be testing?

File: jans-cedarling/cedarling/src/jwt/log_entry.rs [hunk 2]
```diff
@@ -15,15 +15,19 @@ pub struct JwtLogEntry {
 }
 
 impl JwtLogEntry {
-    /// Shorthand for creating a [`LogType::System`] log.
-    pub fn system(msg: String) -> Self {
-        let base = BaseLogEntry::new_opt_request_id(LogType::System, None);
-        Self { base, msg }
+    /// Helper function for creating log messages
+    pub fn new(msg: impl Into<String>, level: LogLevel) -> Self {
```
Comment (0xtinkle) [inline jans-cedarling/cedarling/src/jwt/log_entry.rs]: why `msg: impl Into<String>`? maybe better to define like this?
```
pub fn new(msg: String, level: Option<LogLevel>) -> Self {
        let mut base = BaseLogEntry::new_opt_request_id(LogType::System, None);
        base.set_level(level.unwrap_or(LogLevel::INFO));
        Self { base, msg }
}

**Comment by 0xtinkle** [comment]
> > missing unit test in log_entry.rs
> 
> there's two files with that name:
> 
> * jwt/log_entry.rs
> * log/log_entry.rs
> 
> also, what should we be testing?

I meant jwt/log_entry.rs, specifically new log function you implemented.
```
mod tests {
    use super::*;

    #[test]
    fn test_new() {
        let entry = JwtLogEntry::system("Test message".to_string(), Some(LogLevel::INFO));
        assert_eq!(entry.get_log_level(), Some(LogLevel::INFO));
        assert_eq!(entry.msg, "Test message");
    }

File: jans-cedarling/cedarling/src/log/interface.rs [hunk 3]
```diff
@@ -17,6 +19,14 @@ pub(crate) trait LogWriter {
     fn log_any<T: Loggable>(&self, entry: T);
 }
 
+impl LogWriter for Option<Arc<LogStrategy>> {
```
Comment (0xtinkle) [inline jans-cedarling/cedarling/src/log/interface.rs:22]: can you share what this code is for?
I assume that it's not related to the issue which the PR aims to resolve?

File: jans-cedarling/cedarling/src/jwt/log_entry.rs (hunk 2 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/jwt/log_entry.rs]: i used `msg: impl Into<String>` so that someone using it could call it like this:

```rs
let log_entry = JwtLogEntry::new("error!", level::ERROR);
let log_entry = JwtLogEntry::new(format!("error: {}", err_msg), level::ERROR);
```

if we use `msg: String`, we would have to call `.to_string()` or `.into()` when passing a `&str`.

```rs
let log_entry = JwtLogEntry::new("error!".to_string(), level::ERROR);
```

calling `.into()` on a String is free and should be optimized away at compile time:

```rs
// From (and thus Into) is reflexive
#[stable(feature = "rust1", since = "1.0.0")]
impl<T> From<T> for T {
    /// Returns the argument unchanged.
    #[inline(always)]
    fn from(t: T) -> T {
        t
    }
}
```

---

Also, regarding the logging level. The logs do not get printed at all if it does not have a logging level so it doesn't make sense to have an optional logging level... I don't know why `BaseLogEntry` has an optional logging level.

**Comment by rmarinn** [comment]
> > > missing unit test in log_entry.rs
> > 
> > 
> > there's two files with that name:
> > 
> > * jwt/log_entry.rs
> > * log/log_entry.rs
> > 
> > also, what should we be testing?
> 
> I meant jwt/log_entry.rs, specifically new log function you implemented.
> 
> ```
> mod tests {
>     use super::*;
> 
>     #[test]
>     fn test_new() {
>         let entry = JwtLogEntry::system("Test message".to_string(), Some(LogLevel::INFO));
>         assert_eq!(entry.get_log_level(), Some(LogLevel::INFO));
>         assert_eq!(entry.msg, "Test message");
>     }
> ```

I don't see the point of that... we're just assigning variables and the only reason it wouldn't work is if there's a bug in the compiler.

File: jans-cedarling/cedarling/src/log/interface.rs (hunk 3 above)
Comment (rmarinn) [reply jans-cedarling/cedarling/src/log/interface.rs:22]: Every time i tried to log something, I found myself writing this snippet repeatedly:

```rs
if let Some(logger) = self.logger.as_ref {
    logger.log_any(...)
}
```

It's just for convenience so i can call `log_any` on an `Option<Arc<LogStrategy>>`.

File: jans-cedarling/cedarling/src/jwt/log_entry.rs (hunk 2 above)
Comment (0xtinkle) [reply jans-cedarling/cedarling/src/jwt/log_entry.rs]: It's default coding style. `msg: impl Into<String>` is not well structured code.
Also you do't need to call `.to_string()` or `.into()` every time.
Since BaseLogEntry has an optional logging level for now, we need to follow it.
I guess it's true but if you think, it doesn't make sense, you need to create an issue and handle it in another PR.

File: jans-cedarling/cedarling/src/log/interface.rs (hunk 3 above)
Comment (0xtinkle) [reply jans-cedarling/cedarling/src/log/interface.rs:22]: Every piece of code in the PR should be only related to the issue which needs to be resolved.
For the above purpose, I need to create a separate PR so that it can be tracked properly later.

**Comment by 0xtinkle** [comment]
> > > > missing unit test in log_entry.rs
> > > 
> > > 
> > > there's two files with that name:
> > > 
> > > * jwt/log_entry.rs
> > > * log/log_entry.rs
> > > 
> > > also, what should we be testing?
> > 
> > 
> > I meant jwt/log_entry.rs, specifically new log function you implemented.
> > ```
> > mod tests {
> >     use super::*;
> > 
> >     #[test]
> >     fn test_new() {
> >         let entry = JwtLogEntry::system("Test message".to_string(), Some(LogLevel::INFO));
> >         assert_eq!(entry.get_log_level(), Some(LogLevel::INFO));
> >         assert_eq!(entry.msg, "Test message");
> >     }
> > ```
> 
> I don't see the point of that... we're just assigning variables and the only reason it wouldn't work is if there's a bug in the compiler.

We always need to focus on high-quality code and try to produce 100% test coverage code if possible.
Sometimes, the small thing which was obvious breaks the logic.

**Review by 0xtinkle — APPROVED** [review]
lgtm

**Review by SafinWasi — APPROVED** [review]
Looks good to me, I was able to trigger the warning log.

**Review by moabu — APPROVED** [review]
