### PR TITLE
fix(jans-cedarling): Add namespace support for default entities and parse Cedar JSON format

### LINKED ISSUE #12461: fix(jans-cedarling): Default entities use incorrect namespace causing validation errors
## Bug Description

When using default entities in a policy store, Cedar validation fails with an `UnexpectedEntityType` error because the system uses the hardcoded namespace "Jans" instead of the actual namespace from the policy store.

## Error Message

```
Error: failed to validate Cedar entities: InvalidEntity(UnexpectedEntityType(UnexpectedEntityTypeError { uid: EntityUID(EntityUIDImpl { ty: EntityType(Name(InternalName { id: Id("DefaultEntity"), path: [Id("Jans")], loc: Some(Loc { span: SourceSpan { offset: SourceOffset(0), length: 19 }, src: "Jans::DefaultEntity::\"2694c954f8d8\"" }) })), eid: Eid("2694c954f8d8"), loc: Some(Loc { span: SourceSpan { offset: SourceOffset(0), length: 35 }, src: "Jans::DefaultEntity::\"2694c954f8d8\"" }) }), suggested_types: [EntityType(Name(InternalName { id: Id("DefaultEntity"), path: [Id("Gluu"), Id("Flex"), Id("AdminUI"), Id("Resources")], loc: None }))] }))
```

## Expected Behavior

The default entity should be created with the namespace from the policy store name (e.g., `Gluu::Flex::AdminUI::Resources::Features::"2694c954f8d8"`), matching the schema definition.

## Actual Behavior

The default entity is created with the hardcoded "Jans" namespace (e.g., `Jans::DefaultEntity::"2694c954f8d8"`), which doesn't match the schema and causes validation to fail.

### PR DESCRIPTION
**Pull request by 0xtinkle**
### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

#### Target issue
  
  
  
  
closes #12461

#### Implementation Details
- Removed hardcoded DEFAULT_ENTITY_TYPE constant
- Added UNKNOWN_ENTITY_TYPE constant for error messages
- Updated parse_default_entities() to accept namespace parameter
- Added support for Cedar entity JSON format (with uid field)
- Maintained backward compatibility with legacy format (entity_type field)
- Updated EntityBuilder::new() to accept namespace parameter
- Updated service_factory to pass namespace from policy store
- Updated all test code to pass the namespace parameter

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

## Summary by CodeRabbit

* **New Features**
  * Cedar-format support for default entities (uid, attributes, optional parents).

* **Improvements**
  * Namespace-aware entity type and parent prefixing.
  * Enhanced parsing with per-entity validation, clearer error reporting, and integrated logging.
  * Simplified logger initialization for tests and runtime.
  * Minor control-flow cleanups across parsing and validation paths.

* **Tests / Chores**
  * Tests updated to accommodate expanded builder initialization and test logger.
  * Project Rust edition bumped to 2024.

### CODE REVIEW

**Comment by mo-auto** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/janssenproject/pr-checks/903000d7-aa4f-4042-8c4c-b98a594ff8eb?refs=28c566c8e582d75d5ab735692d2985508242bcbf&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: jans-cedarling/cedarling/src/entity_builder/mod.rs [hunk 1]
```diff
@@ -170,7 +277,8 @@ impl EntityBuilder {
 
         // Parse default entities if provided
         let default_entities = if let Some(entities_data) = default_entities_data {
-            parse_default_entities(entities_data)
+            let ns = namespace.unwrap_or("Unknown");
```
Comment (haileyesus2433) [inline jans-cedarling/cedarling/src/entity_builder/mod.rs]: entities are being created with `Unknown::EntityType`, which doesn’t match any schema and leads to silent failures users won’t see an error, but these entities will later fail Cedar validation i think the best way would be to require namespace to be provided

File: jans-cedarling/cedarling/src/entity_builder/mod.rs [hunk 2]
```diff
@@ -39,15 +39,44 @@ use std::str::FromStr;
...
+            }
+        }
+    }
+    Ok(cedar_attrs)
+}
+
 /// Parse default entities from the provided configuration
 fn parse_default_entities(
     default_entities_data: &HashMap<String, Value>,
+    namespace: &str,
```
Comment (haileyesus2433) [inline jans-cedarling/cedarling/src/entity_builder/mod.rs]: There’s no validation to ensure the namespace is non-empty, follows the valid Cedar identifier format, or avoids unsafe characters. I think It’s best to add these checks at the start of the function.

File: jans-cedarling/cedarling/src/entity_builder/mod.rs [hunk 3]
```diff
@@ -86,51 +115,128 @@ fn parse_default_entities(
...
+                    ) {
+                        // Add namespace if not present
+                        let full_parent_type = if type_v.contains("::") {
+                            type_v.to_string()
+                        } else {
+                            format!("{}::{}", namespace, type_v)
+                        };
+                        
+                        let parent_uid_str = format!("{}::\"{}\"", full_parent_type, id_v);
+                        if let Ok(parent_uid) = EntityUid::from_str(&parent_uid_str) {
```
Comment (haileyesus2433) [inline jans-cedarling/cedarling/src/entity_builder/mod.rs]: Silently ignores if `EntityUid::from_str` fails without logging or warnings about ignored parents

File: jans-cedarling/cedarling/src/entity_builder/mod.rs (hunk 2 above)
Comment (olehbozhok) [reply jans-cedarling/cedarling/src/entity_builder/mod.rs]: Actually namespace can be empty in Cedar. But yeah, if it is empty, we can use `{namespace}::{type}` and need to use `{type}` instead.

Comment (olehbozhok) [reply jans-cedarling/cedarling/src/entity_builder/mod.rs]: resolved in f76546f2af1c6cbdd53d2ec935c47036602e657d

File: jans-cedarling/cedarling/src/entity_builder/mod.rs (hunk 3 above)
Comment (olehbozhok) [reply jans-cedarling/cedarling/src/entity_builder/mod.rs]: resolved in f1e9425ee29164cfcd52bc2dfe28be7197ee5309 , added log message

**Review by olehbozhok — APPROVED** [review]
